FROM openjdk:11

COPY ./target/find-property-0.0.1-SNAPSHOT.jar /usr/app/

WORKDIR /usr/app

RUN sh -c 'touch find-property-0.0.1-SNAPSHOT.jar'

ENTRYPOINT ["java","-jar","find-property-0.0.1-SNAPSHOT.jar"]